'use client';
import { useState } from 'react';

const modules=['Dashboard','Recebimento','Estoque','Endereçamento','Movimentações','Picking','Expedição','Inventário','Relatórios','Impressões','Clientes','Fornecedores','Transportadoras','Fiscal / NF-e','Usuários','Configurações'];
const actions=['Visualizar','Incluir','Alterar','Excluir','Aprovar'];
const profiles=['Administrador','Gestor','Supervisor','Operador','Conferente','Expedição','Fiscal'];

export default function AcessosPage(){
 const [profile,setProfile]=useState('Administrador');
 const [selected,setSelected]=useState<Record<string,boolean>>(()=>Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,m==='Dashboard'||profile==='Administrador']))));
 const [saved,setSaved]=useState(false);
 const toggle=(key:string)=>setSelected(s=>({...s,[key]:!s[key]}));
 const setRow=(m:string,value:boolean)=>setSelected(s=>({...s,...Object.fromEntries(actions.map(a=>[`${m}:${a}`,value]))}));
 const applyProfile=(p:string)=>{setProfile(p);const full=p==='Administrador';setSelected(Object.fromEntries(modules.flatMap(m=>actions.map(a=>[`${m}:${a}`,full||a==='Visualizar'&&(m!=='Configurações'||p==='Gestor')]))));setSaved(false)};
 return <main className="min-h-screen bg-slate-100 text-slate-900 p-4 sm:p-8"><div className="max-w-7xl mx-auto space-y-6">
  <header className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-blue-600 font-bold">ProdLog WMS • Gestão</div><h1 className="text-3xl font-black mt-1">Relação de Acessos</h1><p className="text-slate-500 mt-1">Matriz de permissões por perfil, no padrão de gestão do ProdOS.</p></div><a href="/usuarios" className="border bg-white px-4 py-2.5 rounded-lg text-sm font-semibold">← Usuários</a></header>
  <section className="bg-white border rounded-2xl p-5 flex flex-col md:flex-row gap-4 md:items-end"><label className="text-sm font-semibold flex-1">Perfil<select value={profile} onChange={e=>applyProfile(e.target.value)} className="mt-1 block w-full border rounded-lg px-3 py-2.5">{profiles.map(p=><option key={p}>{p}</option>)}</select></label><button onClick={()=>{setSaved(true);setTimeout(()=>setSaved(false),2500)}} className="bg-blue-600 text-white px-5 py-2.5 rounded-lg font-semibold">Salvar relação de acesso</button></section>
  {saved&&<div className="bg-emerald-50 border border-emerald-200 text-emerald-700 rounded-xl px-4 py-3 text-sm font-semibold">Relação de acesso salva para o perfil {profile}.</div>}
  <section className="bg-white border rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b flex items-center justify-between"><div><h2 className="font-bold text-lg">Permissões por módulo</h2><p className="text-sm text-slate-500">Marque exatamente o que o perfil poderá executar.</p></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="text-left px-5 py-3 min-w-[230px]">Módulo</th>{actions.map(a=><th key={a} className="px-4 py-3 text-center min-w-[105px]">{a}</th>)}<th className="px-4 py-3">Todos</th></tr></thead><tbody className="divide-y">{modules.map(m=><tr key={m}><td className="px-5 py-4 font-semibold">{m}</td>{actions.map(a=>{const k=`${m}:${a}`;return <td key={a} className="text-center"><input aria-label={`${m} ${a}`} type="checkbox" className="h-4 w-4" checked={!!selected[k]} onChange={()=>toggle(k)}/></td>})}<td className="text-center"><input type="checkbox" aria-label={`Todos ${m}`} className="h-4 w-4" checked={actions.every(a=>selected[`${m}:${a}`])} onChange={e=>setRow(m,e.target.checked)}/></td></tr>)}</tbody></table></div></section>
  <section className="grid md:grid-cols-3 gap-4"><div className="bg-white border rounded-2xl p-5"><b>Segurança</b><p className="text-sm text-slate-500 mt-2">Permissões devem ser validadas também no servidor, não apenas ocultadas na interface.</p></div><div className="bg-white border rounded-2xl p-5"><b>Escopo</b><p className="text-sm text-slate-500 mt-2">Acesso pode ser associado à empresa, filial e armazém do usuário.</p></div><div className="bg-white border rounded-2xl p-5"><b>Auditoria</b><p className="text-sm text-slate-500 mt-2">Alterações de acesso devem registrar usuário, data, perfil e mudanças.</p></div></section>
 </div></main>}
