'use client';
import { useState } from 'react';

export default function NotasFiscais(){
 const [modal,setModal]=useState(false); const [status,setStatus]=useState('');
 const [form,setForm]=useState({tipo:'NF-e',cliente:'',natureza:'Venda',serie:'1',numero:'',valor:''});
 const emitir=()=>{if(!form.cliente||!form.valor){setStatus('Preencha cliente e valor.');return}setStatus('NF-e preparada para autorização. A emissão oficial depende do certificado digital e integração com SEFAZ/provedor fiscal.');setModal(false)};
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="max-w-7xl mx-auto space-y-6"><div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-blue-600 font-bold">ProdLog WMS • Fiscal</div><h1 className="text-3xl font-black mt-1">Notas Fiscais</h1><p className="text-slate-500 mt-1">Emissão, acompanhamento e consulta de documentos fiscais.</p></div><a href="/" className="border bg-white px-4 py-2.5 rounded-lg text-sm font-semibold h-fit">← Voltar ao WMS</a></div>
 {status&&<div className="bg-amber-50 border border-amber-200 text-amber-800 rounded-xl p-4 text-sm">{status}</div>}
 <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{[['Emitidas hoje','0'],['Aguardando autorização','0'],['Autorizadas','0'],['Rejeitadas','0']].map(x=><div key={x[0]} className="bg-white border rounded-2xl p-5"><div className="text-xs uppercase text-slate-400 font-semibold">{x[0]}</div><div className="text-3xl font-black mt-2">{x[1]}</div></div>)}</div>
 <section className="bg-white border rounded-2xl shadow-sm overflow-hidden"><div className="p-5 border-b flex justify-between items-center"><div><h2 className="font-bold text-lg">Documentos fiscais</h2><p className="text-xs text-slate-400">Acompanhe NF-e e NFC-e.</p></div><button onClick={()=>setModal(true)} className="bg-blue-600 text-white px-4 py-2.5 rounded-lg font-semibold">+ Emitir NF-e</button></div><div className="p-10 text-center text-slate-400">Nenhuma nota fiscal registrada.</div></section>
 <section className="bg-white border rounded-2xl p-6"><h2 className="font-bold">Integração fiscal necessária</h2><p className="text-sm text-slate-500 mt-2">Para emissão oficial, o ProdLog precisará dos dados fiscais da empresa, certificado digital A1/A3, ambiente de homologação/produção e integração com SEFAZ ou um provedor fiscal. O sistema deverá gerar XML, transmitir, consultar protocolo, armazenar XML/DANFE e registrar cancelamento/carta de correção quando aplicável.</p></section>
 {modal&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-2xl p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Emitir NF-e</h2><button onClick={()=>setModal(false)} className="text-2xl">×</button></div><div className="grid sm:grid-cols-2 gap-4 mt-5">{[['cliente','Cliente'],['natureza','Natureza da operação'],['serie','Série'],['numero','Número'],['valor','Valor total']].map(([k,l])=><label key={k} className="text-sm font-medium text-slate-600">{l}<input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full border rounded-lg px-3 py-2.5" /></label>)}</div><div className="mt-5 bg-slate-50 rounded-lg p-3 text-xs text-slate-500">Este protótipo prepara a operação. A autorização oficial não será simulada.</div><div className="flex justify-end gap-2 mt-6"><button onClick={()=>setModal(false)} className="border px-4 py-2 rounded-lg">Cancelar</button><button onClick={emitir} className="bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold">Preparar NF-e</button></div></div></div>}
 </div></main>
}