'use client';
import { useState } from 'react';

type Tipo = 'Clientes' | 'Fornecedores';
type Pessoa = { id:number; nome:string; documento:string; cidade:string; contato:string; status:string };

export default function Cadastros(){
 const [tipo,setTipo]=useState<Tipo>('Clientes');
 const [rows,setRows]=useState<Pessoa[]>([]);
 const [modal,setModal]=useState(false);
 const [form,setForm]=useState({nome:'',documento:'',cidade:'',contato:''});
 const save=()=>{if(!form.nome||!form.documento)return;setRows(v=>[...v,{id:Date.now(),...form,status:'Ativo'}]);setForm({nome:'',documento:'',cidade:'',contato:''});setModal(false)};
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="max-w-7xl mx-auto space-y-6">
  <div className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-blue-600 font-bold">ProdLog WMS • Cadastros</div><h1 className="text-3xl font-black mt-1">Clientes e Fornecedores</h1><p className="text-slate-500 mt-1">Cadastro comercial próprio de cada armazém.</p></div><a href="/" className="border bg-white px-4 py-2.5 rounded-lg text-sm font-semibold h-fit">← Voltar ao WMS</a></div>
  <div className="bg-white border rounded-2xl p-2 flex gap-2"><button onClick={()=>setTipo('Clientes')} className={`flex-1 px-4 py-3 rounded-xl font-semibold ${tipo==='Clientes'?'bg-blue-600 text-white':'hover:bg-slate-100'}`}>Clientes</button><button onClick={()=>setTipo('Fornecedores')} className={`flex-1 px-4 py-3 rounded-xl font-semibold ${tipo==='Fornecedores'?'bg-blue-600 text-white':'hover:bg-slate-100'}`}>Fornecedores</button></div>
  <section className="bg-white border rounded-2xl overflow-hidden shadow-sm"><div className="p-5 border-b flex justify-between items-center"><div><h2 className="font-bold text-lg">{tipo}</h2><p className="text-xs text-slate-400">Dados vinculados ao armazém atual.</p></div><button onClick={()=>setModal(true)} className="bg-blue-600 text-white px-4 py-2.5 rounded-lg font-semibold">+ Novo {tipo==='Clientes'?'cliente':'fornecedor'}</button></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{['Nome / Razão social','CPF/CNPJ','Cidade','Contato','Status','Ações'].map(h=><th key={h} className="text-left px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.nome}</td><td className="px-5 py-4 font-mono">{r.documento}</td><td className="px-5 py-4">{r.cidade||'—'}</td><td className="px-5 py-4">{r.contato||'—'}</td><td className="px-5 py-4"><span className="bg-emerald-50 text-emerald-700 px-2 py-1 rounded-full text-xs">Ativo</span></td><td className="px-5 py-4 text-blue-600 font-semibold">Editar</td></tr>)}{!rows.length&&<tr><td colSpan={6} className="p-12 text-center text-slate-400">Nenhum {tipo.toLowerCase().slice(0,-1)} cadastrado.</td></tr>}</tbody></table></div></section>
  {modal&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-xl p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Novo {tipo==='Clientes'?'cliente':'fornecedor'}</h2><button onClick={()=>setModal(false)} className="text-2xl">×</button></div><div className="grid sm:grid-cols-2 gap-4 mt-5">{[['nome','Nome / Razão social'],['documento','CPF / CNPJ'],['cidade','Cidade / UF'],['contato','Telefone / E-mail']].map(([k,l])=><label key={k} className="text-sm font-medium text-slate-600">{l}<input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full border rounded-lg px-3 py-2.5" /></label>)}</div><div className="flex justify-end gap-2 mt-6"><button onClick={()=>setModal(false)} className="border px-4 py-2 rounded-lg">Cancelar</button><button onClick={save} className="bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold">Salvar cadastro</button></div></div></div>}
 </div></main>
}