'use client';
import { useEffect, useState } from 'react';
type Tipo='clientes'|'fornecedores'|'transportadoras';
type Pessoa={id:string;nome:string;documento:string;cidade:string|null;contato:string|null;email:string|null;ativo:boolean};
const labels:Record<Tipo,string>={clientes:'Clientes',fornecedores:'Fornecedores',transportadoras:'Transportadoras'};

export default function Cadastros(){
 const [tipo,setTipo]=useState<Tipo>('clientes'); const [rows,setRows]=useState<Pessoa[]>([]); const [modal,setModal]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [companyId,setCompanyId]=useState(''); const [form,setForm]=useState({nome:'',documento:'',cidade:'',contato:'',email:''});
 useEffect(()=>{let id=localStorage.getItem('prodlog_company_id')||''; if(id){setCompanyId(id);return;} fetch('/api/master/empresas').then(r=>r.json()).then(x=>{const first=x?.find((e:any)=>e.status==='Ativa'); if(first){localStorage.setItem('prodlog_company_id',first.id);setCompanyId(first.id)} else setError('Cadastre uma empresa ativa na Administração MASTER antes de usar os cadastros.')}).catch(()=>setError('Não foi possível carregar as empresas.'))},[]);
 useEffect(()=>{if(!companyId)return; setLoading(true);setError(''); fetch(`/api/cadastros?companyId=${encodeURIComponent(companyId)}&type=${tipo}`).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||'Erro ao carregar');setRows(x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[companyId,tipo]);
 const save=async()=>{if(!form.nome||!form.documento)return alert('Informe nome/razão social e CPF/CNPJ.'); if(!companyId)return alert('Selecione uma empresa ativa.'); const r=await fetch('/api/cadastros',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({companyId,type:tipo,...form})});const x=await r.json();if(!r.ok)return alert(x.error||'Não foi possível salvar.');setRows(v=>[x,...v]);setForm({nome:'',documento:'',cidade:'',contato:'',email:''});setModal(false)};
 const remove=async(id:string)=>{if(!confirm('Excluir este cadastro?'))return;const r=await fetch(`/api/cadastros?companyId=${encodeURIComponent(companyId)}&type=${tipo}&id=${id}`,{method:'DELETE'});const x=await r.json();if(!r.ok)return alert(x.error||'Não foi possível excluir.');setRows(v=>v.filter(a=>a.id!==id));};
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="max-w-7xl mx-auto space-y-6"><header className="flex flex-col sm:flex-row sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[.2em] text-blue-600 font-bold">ProdLog WMS • Cadastros</div><h1 className="text-3xl font-black mt-1">Clientes, Fornecedores e Transportadoras</h1><p className="text-slate-500 mt-1">Dados persistidos no banco individual da empresa selecionada.</p></div><div className="flex gap-2"><a href="/" className="border bg-white px-4 py-2.5 rounded-lg font-semibold">← WMS</a><button onClick={()=>setModal(true)} className="bg-blue-600 text-white px-4 py-2.5 rounded-lg font-semibold">+ Novo cadastro</button></div></header>
 <div className="flex gap-2 overflow-x-auto">{(Object.keys(labels) as Tipo[]).map(x=><button key={x} onClick={()=>setTipo(x)} className={`px-4 py-2.5 rounded-lg font-semibold ${tipo===x?'bg-blue-600 text-white':'bg-white border'}`}>{labels[x]}</button>)}</div>
 {error&&<div className="bg-rose-50 border border-rose-200 text-rose-700 p-4 rounded-xl">{error}</div>}
 <section className="bg-white border rounded-2xl overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{['Nome/Razão social','CPF/CNPJ','Cidade/UF','Contato','E-mail','Status','Ações'].map(h=><th key={h} className="text-left px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={7} className="p-12 text-center">Carregando...</td></tr>:rows.map(r=><tr key={r.id}><td className="px-5 py-4 font-semibold">{r.nome}</td><td className="px-5 py-4 font-mono">{r.documento}</td><td className="px-5 py-4">{r.cidade||'—'}</td><td className="px-5 py-4">{r.contato||'—'}</td><td className="px-5 py-4">{r.email||'—'}</td><td className="px-5 py-4 text-emerald-700">{r.ativo?'Ativo':'Inativo'}</td><td className="px-5 py-4"><button onClick={()=>remove(r.id)} className="text-rose-600 font-semibold">Excluir</button></td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={7} className="p-12 text-center text-slate-400">Nenhum cadastro.</td></tr>}</tbody></table></div></section>
 {modal&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl w-full max-w-xl p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Novo {labels[tipo].slice(0,-1)}</h2><button onClick={()=>setModal(false)} className="text-2xl">×</button></div><div className="grid sm:grid-cols-2 gap-4 mt-5">{[['nome','Nome / Razão social'],['documento','CPF / CNPJ'],['cidade','Cidade / UF'],['contato','Telefone'],['email','E-mail']].map(([k,l])=><label key={k} className="text-sm font-medium text-slate-600">{l}<input value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full border rounded-lg px-3 py-2.5" /></label>)}</div><div className="flex justify-end gap-2 mt-6"><button onClick={()=>setModal(false)} className="border px-4 py-2 rounded-lg">Cancelar</button><button onClick={save} className="bg-blue-600 text-white px-4 py-2 rounded-lg font-semibold">Salvar cadastro</button></div></div></div>}</div></main>;
}