import { NextResponse } from 'next/server';
import { masterSql, ensureMasterSchema } from '@/lib/master-db';
import { tenantSql } from '@/lib/tenant-db';

const TYPES = ['clientes', 'fornecedores', 'transportadoras'] as const;
type TypeKey = typeof TYPES[number];
function validType(value: string): TypeKey { if ((TYPES as readonly string[]).includes(value)) return value as TypeKey; throw new Error('Tipo de cadastro inválido.'); }
async function getTenantDb(companyId: string) { await ensureMasterSchema(); const rows = await masterSql`SELECT database_url FROM master_empresas WHERE id=${companyId} AND status='Ativa' LIMIT 1`; if (!rows[0]?.database_url) throw new Error('Banco da empresa não configurado.'); return tenantSql(rows[0].database_url); }
async function ensureTables(sql: ReturnType<typeof tenantSql>) { await sql`CREATE EXTENSION IF NOT EXISTS pgcrypto`; await sql`CREATE TABLE IF NOT EXISTS clientes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, documento text NOT NULL, cidade text, contato text, email text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`; await sql`CREATE TABLE IF NOT EXISTS fornecedores (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, documento text NOT NULL, cidade text, contato text, email text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`; await sql`CREATE TABLE IF NOT EXISTS transportadoras (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL, documento text, cidade text, contato text, email text, ativo boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`; await sql`ALTER TABLE clientes ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()`; await sql`ALTER TABLE fornecedores ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()`; await sql`ALTER TABLE transportadoras ADD COLUMN IF NOT EXISTS cidade text`; await sql`ALTER TABLE transportadoras ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now()`; }
async function selectRows(sql: ReturnType<typeof tenantSql>, type: TypeKey) { if (type === 'clientes') return sql`SELECT id,nome,documento,cidade,contato,email,ativo,created_at,updated_at FROM clientes ORDER BY created_at DESC`; if (type === 'fornecedores') return sql`SELECT id,nome,documento,cidade,contato,email,ativo,created_at,updated_at FROM fornecedores ORDER BY created_at DESC`; return sql`SELECT id,nome,documento,cidade,contato,email,ativo,created_at,updated_at FROM transportadoras ORDER BY created_at DESC`; }
export async function GET(request: Request) { try { const u=new URL(request.url); const companyId=u.searchParams.get('companyId'); const type=validType(u.searchParams.get('type')||'clientes'); if(!companyId)return NextResponse.json({error:'companyId é obrigatório.'},{status:400}); const sql=await getTenantDb(companyId); await ensureTables(sql); return NextResponse.json(await selectRows(sql,type)); } catch(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao consultar cadastros.'},{status:500});} }
export async function POST(request: Request) { try { const b=await request.json(); const type=validType(b.type||'clientes'); if(!b.companyId||!b.nome?.trim()||!b.documento?.trim())return NextResponse.json({error:'Empresa, nome/razão social e CPF/CNPJ são obrigatórios.'},{status:400}); const sql=await getTenantDb(b.companyId); await ensureTables(sql); const nome=b.nome.trim(),documento=b.documento.trim(),cidade=b.cidade||null,contato=b.contato||null,email=b.email||null,ativo=b.ativo!==false; let rows; if(type==='clientes')rows=await sql`INSERT INTO clientes(nome,documento,cidade,contato,email,ativo) VALUES(${nome},${documento},${cidade},${contato},${email},${ativo}) RETURNING *`; else if(type==='fornecedores')rows=await sql`INSERT INTO fornecedores(nome,documento,cidade,contato,email,ativo) VALUES(${nome},${documento},${cidade},${contato},${email},${ativo}) RETURNING *`; else rows=await sql`INSERT INTO transportadoras(nome,documento,cidade,contato,email,ativo) VALUES(${nome},${documento},${cidade},${contato},${email},${ativo}) RETURNING *`; return NextResponse.json(rows[0],{status:201}); }catch(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao cadastrar.'},{status:500});} }
export async function PATCH(request: Request) { try { const b=await request.json(); const type=validType(b.type||'clientes'); if(!b.companyId||!b.id)return NextResponse.json({error:'Empresa e id são obrigatórios.'},{status:400}); const sql=await getTenantDb(b.companyId); await ensureTables(sql); const nome=b.nome?.trim()||null,documento=b.documento?.trim()||null,cidade=b.cidade??null,contato=b.contato??null,email=b.email??null,ativo=b.ativo!==false; let rows; if(type==='clientes')rows=await sql`UPDATE clientes SET nome=COALESCE(${nome},nome),documento=COALESCE(${documento},documento),cidade=${cidade},contato=${contato},email=${email},ativo=${ativo},updated_at=now() WHERE id=${b.id} RETURNING *`; else if(type==='fornecedores')rows=await sql`UPDATE fornecedores SET nome=COALESCE(${nome},nome),documento=COALESCE(${documento},documento),cidade=${cidade},contato=${contato},email=${email},ativo=${ativo},updated_at=now() WHERE id=${b.id} RETURNING *`; else rows=await sql`UPDATE transportadoras SET nome=COALESCE(${nome},nome),documento=${documento},cidade=${cidade},contato=${contato},email=${email},ativo=${ativo},updated_at=now() WHERE id=${b.id} RETURNING *`; if(!rows[0])return NextResponse.json({error:'Registro não encontrado.'},{status:404}); return NextResponse.json(rows[0]); }catch(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao atualizar.'},{status:500});} }
export async function DELETE(request: Request) { try { const u=new URL(request.url),companyId=u.searchParams.get('companyId'),id=u.searchParams.get('id'),type=validType(u.searchParams.get('type')||'clientes'); if(!companyId||!id)return NextResponse.json({error:'companyId e id são obrigatórios.'},{status:400}); const sql=await getTenantDb(companyId); await ensureTables(sql); let rows; if(type==='clientes')rows=await sql`DELETE FROM clientes WHERE id=${id} RETURNING id`; else if(type==='fornecedores')rows=await sql`DELETE FROM fornecedores WHERE id=${id} RETURNING id`; else rows=await sql`DELETE FROM transportadoras WHERE id=${id} RETURNING id`; if(!rows[0])return NextResponse.json({error:'Registro não encontrado.'},{status:404}); return NextResponse.json({ok:true}); }catch(e:unknown){return NextResponse.json({error:e instanceof Error?e.message:'Erro ao excluir.'},{status:500});} }
